### ISSUE TITLE
Bug: Re-connection to the DB

### ISSUE THREAD

**Issue by iliesh** [surrealdb/surrealdb.go#110]
### Describe the bug

When the application is running, and the DB is restarted, then the application panic with the following stack:
```
panic: repeated read on failed websocket connection

goroutine 50 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000e0580)
        /home/admin/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1030 +0x4f4
github.com/gorilla/websocket.(*Conn).ReadMessage(0x129dfa0?)
        /home/admin/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:1093 +0x2f
github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).read(0xc00039c080, {0xca5720, 0xc0003f4480})
        /home/admin/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:140 +0x45
github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).initialize.func1()
        /home/admin/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:167 +0xac
created by github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).initialize in goroutine 1
        /home/admin/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:160 +0x8e
exit status 2
```

### Steps to reproduce

run an application and then stop surrealdb

### Expected behaviour

reconnect or return back an error to the application, and let developer decide what to do

### SurrealDB version

1.0.0+20230913.54aedcd for linux on x86_64

### Contact Details

iliusha.md@gmail.com

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElecTwix** [comment]
Thanks for the issue.
As you said It needs to reconnect after the websocket connection is broken after other PRs merged I will look into this.

**Comment by phughk** [comment]
We do want a shared configuration between drivers about how we handle network traffic (timeouts, reconnects, circuiting breaking strategies etc). Overall this would need to be standardised but for now we could add a helper.

Would recommend adhering to existing golang standards.

**Comment by mumoshu** [comment]
Thank you @0xCA!

Ah, that makes sense. It aligns with what I've imagined after reading the SDK code recently.

So, the way our WebSocketConnection is designed to work is like, `keep reading messages until the underlying TCP session gets closed`. Transient errors should be handled by gorilla/websocket and our WebSocketConnection. The original error, `repeated read on failed websocket connection`, reported in this issue, was more about programming errors related to this transient error handling, which has already been fixed.

However, it is also true that we have no feature to inform the SDK consumer whether the connection is still alive, i.e., whether they need to recreate the WebSocketConnection instance or not.

I can definitely add the method for checking liveness of the connection.
Would it be enough for you?

I also imagine we could explore options to "abstract away" reconnection, so that errors due to reconnection would appear as transit errors to the consumer of the SDK.

**Comment by mumoshu** [comment]
After some tinkering, I realized it is much simpler and headache-free to hide the connection state check feature and provide the SDK consumer a toggle to configure reconnection check interval only.

Notes:

- I added the option to specify reconnection check interval to `Connect` rather than `New`, because `New` is deprecated in v0.6.0 due to lack of context suppport
- No `DB.IsClosed` or `surrealDB.IsClosed(*DB)` for the reason mentioned above
- Error types- I think we can address those separately, because it is unnecessary to implement the reconnection feature. The SDK already had some logic to decide which Read error is transient or permanent, and the reconnection feature is indirectly built on top of that.
- Re: mutexes; Yeah, I needed ones, but used differently than I initially thought. I built the feature around the idea of state machines so that you don't need to use multiple concurrent locks to prevent undefined behaviors, which is prone to deadlocks 🤦 

#267

**Comment by 0xCA** [comment]
> New is deprecated in v0.6.0 due to lack of context support

Deprecated yet still present? And not marked as deprecated.

Even if the reconnection is managed internally, DB.IsConnected and errors are still necessary to handle an interrupted connection by buffering or switching to another node.

About the reconnection mechanism itself:
- Should be triggered not only by a periodic healthcheck, but also by a failed RPC, immediately.
- Should use exponential backoff instead of a constant period, and the period should be decoupled from the healthcheck interval.

Example backoff code from my balancer:

```
// RecordFailure records a failure and calculates the next backoff time
func (h *HostClient) RecordFailure() {
	h.mutex.Lock()
	defer h.mutex.Unlock()

	h.IsHealthy = false
	h.FailureCount++
	h.LastFailure = time.Now()

	// Exponential backoff: 2^failureCount seconds, max 5 minutes
	backoffSeconds := math.Min(math.Pow(2, float64(h.FailureCount)), 300)
	// Add jitter to prevent thundering herd
	jitter := rand.Float64() * 0.1 * backoffSeconds
	h.BackoffUntil = time.Now().Add(time.Duration(backoffSeconds+jitter) * time.Second)
}
```
Yes, I apply jitter to the max wait time too, making it a non-strict limit. This is intentional.

**Comment by 0xCA** [comment]
> I'd rather fail-fast in that case so that multiple RPCs do not contend on the reconnecting(ant still not working) connection
> How did you design that part?

I mean it as independent things.
RPC fails, we return "node failure" error immediately, balancer switches to a different node for the very next RPC.
At the same time, client-internally, it triggers a reconnection loop (with backoff).
In this case, balancer only have to check IsConnected() on the client every second or so, if backoff is handled by the client itself.

In summary, we _do_ fail-fast the client (node), and leave it to itself, only periodically checking if it's back online.

In case of a single-node setup with no balancer, client should just immediately return a node failure error to every RPC while it's not connected, effectively rejecting any attempt to use it. All while allowing to check connectivity via IsConnected().

**Comment by mumoshu** [comment]
Hey @0xCA! That makes sense. Thank you very much for sharing your insights!

Some update- I've just merged #279, which I believe was necessary to properly auto-reconnect things transparently to the app.

For your use case, I think these two are handy:

- The `connection.Connection` interface now includes `SignIn`, `SignUp`, `Authenticate`, `Invalidate` so that a high-level connection implementation can use it to save and restore session transparently to the consumer.
- There's also the `connection.WebSocketConnection` interface, which is implemented using `gorilla/websocket` and `gws`. It has `IsClosed()` which can also be used by a high-level library like the auto-reconnection Connection implementation (I named it `rews` anyway).

You should be able to enhance the `rews` library I've written (the auto-reconnecting websocket connection implementation) to support triggering reconnection on rpc failure like you explained, or use it as a reference to your loadbalancing connection adopting the new interface. 

WDYT?
Thank you in advance for your support!

**Comment by mumoshu** [comment]
Hi @0xCA!

Honestly speaking, I don't have 100% confidence in the SDK's API surface yet, so it can't "finalize" it anytime soon.

However, I will try to scope things in/out and cut v1 in a month or two. Once v1 is released, you can expect all the public APIs of the SDK to maintain backward-compatibility until v2, according to semver.

The next release v0.7.0 will have a new `WebSocketConnection` interface with everything in `Connection` interface with only one addition, the `IsClosed() bool` function, to let the consumer see if it is closed or not.

The only important contract around all the Connection implementations is that once closed, it cannot be connected again. So `rews` starts a reconnection loop when `Connect` is called on it, and stops the loop when `Close` is called. Under the hood, `rews` recreates the underlying connection when it is closed.

I eliminated `ConnectOption` and the options to `Connect` in a recent pull request because it wasn't a good idea.

Also, FYI, here's how you could initialize `*surrealdb.DB` using `rews`.

https://github.com/surrealdb/surrealdb.go/blob/f4d86a8dac8ddddd0027572584c076918911ce91/pkg/connection/integration/rews_test.go#L117-L122

You basically give `rews` a constructor for the underlying connection implementation (gorilla or gws or whatever implementation of `connection.WebSocketConnection`). This is a direct translation of the fact that `rews` recreates the underlying connection once it gets closed (by calling `Close` or by connection closure has been detected by write errors).

**Comment by mumoshu** [comment]
Let's move over to #280!
