### ISSUE TITLE
Bug: UnmarshalRaw panics when unmarshalling object

### ISSUE THREAD

**Issue by AAA1exa8** [surrealdb/surrealdb.go#139]
### Describe the bug

When .Query() returns object unmarshall raw panics with  
```
goroutine 1 [running]:
github.com/surrealdb/surrealdb%2ego.UnmarshalRaw({0x635ea0?, 0xc00022e1f8?}, {0x630aa0, 0xc000224430})
        ~/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/db.go:119 +0x2e5
main.main()
        /paht/to/file/side.go:39 +0x309
exit status 2

```
the crash happens because of this cast in UnmarshallRaw
```go
result := responseObj["result"]
if len(result.([]interface{})) == 0 {
	return false, nil
}
```

### Steps to reproduce

```go
package main

import (
	"fmt"

	"github.com/surrealdb/surrealdb.go"
)

type Id struct {
	Id int `json:"id"`
}

func main() {
	db, err := surrealdb.New("ws://localhost:8000/rpc")
	if err != nil {
		fmt.Print(err.Error())
		return
	}
	defer db.Close()
	if _, err = db.Signin(map[string]interface{}{
		"user": "root",
		"pass": "root",
	}); err != nil {
		fmt.Print(err.Error())
		return
	}
	if _, err = db.Use("namespace", "database"); err != nil {
		fmt.Print(err.Error())
		return
	}
	iddb, err := db.Query(`RETURN {
		id: 3
	}`, nil)
	if err != nil {
		fmt.Print(err.Error())
		return
	}
	var id Id
	_, err = surrealdb.UnmarshalRaw(iddb, &id)
	if err != nil {
		fmt.Print(err.Error())
	}
	fmt.Print(id)

}
```

### Expected behaviour

UnmarashalRaw should correctly unmarshall the response

There is workaround by doing
```go
iddb, err := db.Query(`RETURN [{
	id: 3
}]`, nil)
var id []Id
_, err = surrealdb.UnmarshalRaw(iddb, &id)
```

### SurrealDB version

1.5.0 for linux on x86_64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AAA1exa8** [comment]
I've just quickly went through the code of the current commit and it seems the RawQuery type still expects array
```go
type RawQuery[I any] struct {
	Status string `json:"status"`
	Time   string `json:"time"`
	Result []I    `json:"result"`
	Detail string `json:"detail"`
}
```
this is the code I ran with the current commit of `main`

(the workaround still works)
```go
package main

import (
	"fmt"

	"github.com/surrealdb/surrealdb.go"
	"github.com/surrealdb/surrealdb.go/pkg/conn/gorilla"
	"github.com/surrealdb/surrealdb.go/pkg/marshal"
)

type Id struct {
	Id int `json:"id"`
}

func main() {
	ws := gorilla.Create()
	conn, err := ws.Connect("ws://localhost:8000/rpc")
	if err != nil {
		fmt.Print(err.Error())
		return
	}
	db, err := surrealdb.New("ws://localhost:8000/rpc", conn)
	if err != nil {
		fmt.Print(err.Error())
		return
	}
	defer db.Close()
	if _, err = db.Signin(&surrealdb.Auth{
		Namespace: "namespace",
		Database:  "database",
		Username:  "root",
		Password:  "root",
	}); err != nil {
		fmt.Print(err.Error())
		return
	}
	iddb, err := db.Query(`RETURN {
		id: 3
	}`, nil)
	if err != nil {
		fmt.Print(err.Error())
		return
	}
	var id []marshal.RawQuery[Id]
	err = marshal.UnmarshalRaw(iddb, &id)
	if err != nil {
		fmt.Print(err.Error())
	}
	fmt.Print(id)

}
```
it got fixed for me when I changed the type of result to `I` instead of `[]I`

it works as expected when I do 
```go
iddb, err := db.Query(`RETURN [{
	id: 3
}]`, nil)
var id []marshal.RawQuery[[]Id]
err = marshal.UnmarshalRaw(iddb, &id)
```

I can open PR with the fix

**Comment by ElecTwix** [comment]
> I can open PR with the fix

Feel free to Open PR, all contributions are welcome.
As far as I remember `SmartUnmarshal` also uses that maybe it can need a bit of refactoring in there too.

**Comment by AAA1exa8** [comment]
its one line change in SmartUnmarshall

**Comment by tobiemh** [comment]
Hi @AAA1exa8 thanks so much for opening this issue 😃 👍. Since the date of this issue, the [Golang SDK](https://github.com/surrealdb/surrealdb.go) has seen significant changes, with support for both HTTP and WebSocket connections, full support of the SurrealDB RPC methods, a binary communication protocol using CBOR, and support for embedding SurrealDB in memory and with SurrealKV coming soon. As a result, I'm going to close this issue as this issue is no longer relevant in the latest code base 🚀 🎉.
