### ISSUE TITLE
Consider switching WebSocket library

### ISSUE THREAD

**Issue by JohnKinyanjui** [surrealdb/surrealdb.go#144]
### Describe the bug

Am not sure but i think this error might by gorilla websocket please consider to switch to a better library, it unable to handle websocket correctly but if its from my end let me know

### Steps to reproduce

this is my simple middleware in golang for echo, i use it to authorize tokens on the rest api

```go
func AuthMiddleware(next echo.HandlerFunc) echo.HandlerFunc {

	return func(c echo.Context) error {
		token := c.Request().Header.Get("Authorization")
		tokenString := strings.Split(token, " ")
		if len(tokenString) != 2 {
			return c.JSON(http.StatusUnauthorized, map[string]string{"message": "missing or invalid token"})
		}

		db, err := database.Connection(tokenString[1])
		if err != nil {
			return c.JSON(http.StatusUnauthorized, map[string]string{"message": "invalid token"})
		}
		defer db.Close()

		c.Set("db", db)

		return next(c)
	}
}

```

### Expected behaviour

```bash
panic: repeated read on failed websocket connection

goroutine 315 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc000557b80)
        C:/Users/hp/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1055 +0x28d
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc00025ff70?)
        C:/Users/hp/go/pkg/mod/github.com/gorilla/websocket@v1.5.1/conn.go:1120 +0x13
github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).read(0xc0005b04e0?, {0x12f51e0, 0xc0003359e0})
        C:/Users/hp/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:140 +0x25
github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).initialize.func1()
        C:/Users/hp/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:167 +0x5e
created by github.com/surrealdb/surrealdb.go/internal/websocket.(*WebSocket).initialize in goroutine 351
        C:/Users/hp/go/pkg/mod/github.com/surrealdb/surrealdb.go@v0.2.1/internal/websocket/ws.go:160 +0x4f
```

### SurrealDB version

1.5.4 for windows on x86_64

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ElecTwix** [comment]
> Am not sure but i think this error might by gorilla websocket please consider to switch to a better library, it unable to handle websocket correctly but if its from my end let me know

I did propose to switch long before. it wasn't accepted https://github.com/surrealdb/surrealdb.go/pull/127. than created [PR](https://github.com/surrealdb/surrealdb.go/pull/143) to replace WS, which is still not reviewed.

**Comment by mumoshu** [comment]
Therefore, migrating to another WebSocket library for reliability reasons is no longer advisable. If we do, we should establish a benchmark that compares how the SDK behaves across different WebSocket libraries, and decide based on the results.

If anyone has numbers/data/etc about real issues that might be addressed by migrating to another WebSocket library, please let me know!

Thank you in advance for your help 🙏

**Comment by 0xCA** [comment]
Of course it would work!
However, on one hand this seems ideal, on the other, this requires far more work to support both, and even a generic bring-your-own one.

**Comment by mumoshu** [comment]
Hi @0xCA! Thank you very much for your confirmation and feedback!

Yeah, I hear you. It might try anyway, and see if it's really feasible.

Optimistically, I could simply reuse the existing `Connection` abstraction, which is currently implemented by HTTP and WebSocket (gorilla/websocket).
Given `gws` seems to provide a socket-like interface to WebSocket, it is probably straightforward to write a `Connection` implementation for gws, following our existing implementation which also uses the socket-like interface provided by gorilla/websocket...
